from enum import StrEnum


class AssetType(StrEnum):
    COMMON_STOCK = "COMMON_STOCK"
    ADR = "ADR"
    ETF = "ETF"
    ETN = "ETN"
    DEBT_SECURITY = "DEBT_SECURITY"
    CEF = "CEF"
    PREFERRED = "PREFERRED"
    WARRANT = "WARRANT"
    RIGHT = "RIGHT"
    UNIT = "UNIT"
    SPAC = "SPAC"
    SHELL = "SHELL"


class ScannerType(StrEnum):
    RERATING = "RERATING"
    GROWTH_PULLBACK = "GROWTH_PULLBACK"
    BIOTECH_CATALYST = "BIOTECH_CATALYST"


class Regime(StrEnum):
    GREEN = "GREEN"
    YELLOW = "YELLOW"
    RED = "RED"


class CatalystGrade(StrEnum):
    A = "A"
    B = "B"
    C = "C"


class ScanStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class EvaluationStatus(StrEnum):
    COMPLETE = "COMPLETE"
    DATA_INCOMPLETE = "DATA_INCOMPLETE"


class DataQualitySeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class RejectionCode(StrEnum):
    GOING_CONCERN = "GOING_CONCERN"
    BANKRUPTCY_RISK = "BANKRUPTCY_RISK"
    FINANCIAL_STATEMENTS_UNRELIABLE = "FINANCIAL_STATEMENTS_UNRELIABLE"
    TRADING_HALTED = "TRADING_HALTED"
    UNRESOLVED_RESTATEMENT = "UNRESOLVED_RESTATEMENT"
    FRAUD_RISK = "FRAUD_RISK"
    LIQUIDITY_TOO_LOW = "LIQUIDITY_TOO_LOW"
    PRICE_TOO_LOW = "PRICE_TOO_LOW"
    MARKET_CAP_TOO_LOW = "MARKET_CAP_TOO_LOW"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    INVALID_ASSET_TYPE = "INVALID_ASSET_TYPE"
    INVALID_EXCHANGE = "INVALID_EXCHANGE"
    INACTIVE_SECURITY = "INACTIVE_SECURITY"
    UPSIDE_BELOW_15 = "UPSIDE_BELOW_15"
    NO_VALID_INVALIDATION = "NO_VALID_INVALIDATION"
    UNVERIFIED_ONLY_CATALYST = "UNVERIFIED_ONLY_CATALYST"
    BIOTECH_RUNWAY_BELOW_9M = "BIOTECH_RUNWAY_BELOW_9M"
    THESIS_BROKEN = "THESIS_BROKEN"
    DATA_INSUFFICIENT = "DATA_INSUFFICIENT"
